import { db } from '../src/lib/db';
import { hashPassword } from '../src/lib/password';

async function main() {
  console.log('Seeding database...');

  // Clear existing data in reverse dependency order
  console.log('Clearing existing data...');
  await db.order.deleteMany();
  await db.reservation.deleteMany();
  await db.chatSession.deleteMany();
  await db.itinerary.deleteMany();
  await db.restaurant.deleteMany();
  await db.venue.deleteMany();
  await db.user.deleteMany();

  // ─── Seed Users ─────────────────────────────────────────────────────────────
  console.log('Seeding users...');
  const users = await Promise.all([
    db.user.create({
      data: {
        email: 'admin@planner.com',
        name: '管理员',
        password: hashPassword('admin123'),
        role: 'admin',
        phone: '13800000001',
      },
    }),
    db.user.create({
      data: {
        email: 'xiaoming@example.com',
        name: '小明',
        password: hashPassword('user123'),
        role: 'user',
        district: '朝阳区',
        phone: '13800000002',
      },
    }),
    db.user.create({
      data: {
        email: 'lisi@example.com',
        name: '李四',
        password: hashPassword('user123'),
        role: 'user',
        district: '海淀区',
        phone: '13800000003',
      },
    }),
  ]);

  // ─── Seed Venues (40+ entries) ──────────────────────────────────────────────
  console.log('Seeding venues...');

  const venueData = [
    // ── Parks (公园) ─────────────────────────────────────────────────────────
    {
      name: '朝阳公园',
      type: 'park',
      district: '朝阳区',
      address: '北京市朝阳区朝阳公园南路1号',
      latitude: 39.9346,
      longitude: 116.4744,
      rating: 4.3,
      description: '北京四环内最大的城市公园，湖光山色，适合散步、划船和亲子活动。',
      priceLevel: 1,
      openTime: '06:00',
      closeTime: '21:00',
      avgVisitMins: 150,
      childFriendly: true,
      dietFriendly: false,
      tags: '公园,湖泊,划船,亲子,散步,跑步',
      imageUrl: '',
      capacity: 8000,
      currentLoad: 35,
      phone: '010-65065409',
    },
    {
      name: '奥林匹克公园',
      type: 'park',
      district: '朝阳区',
      address: '北京市朝阳区北辰东路15号',
      latitude: 39.9929,
      longitude: 116.3918,
      rating: 4.5,
      description: '2008年奥运会主场馆所在地，鸟巢和水立方坐落于此，是北京的地标性公园。',
      priceLevel: 1,
      openTime: '06:00',
      closeTime: '21:00',
      avgVisitMins: 180,
      childFriendly: true,
      dietFriendly: false,
      tags: '公园,奥运,鸟巢,水立方,地标,跑步',
      imageUrl: '',
      capacity: 12000,
      currentLoad: 55,
      phone: '010-84986856',
    },
    {
      name: '颐和园',
      type: 'park',
      district: '海淀区',
      address: '北京市海淀区新建宫门路19号',
      latitude: 39.9999,
      longitude: 116.2755,
      rating: 4.8,
      description: '中国现存最大的皇家园林，以昆明湖和万寿山为主景，是世界文化遗产。',
      priceLevel: 2,
      openTime: '06:30',
      closeTime: '18:00',
      avgVisitMins: 240,
      childFriendly: true,
      dietFriendly: false,
      tags: '公园,皇家园林,世界遗产,昆明湖,万寿山,古建筑',
      imageUrl: '',
      capacity: 15000,
      currentLoad: 68,
      phone: '010-62881144',
    },
    {
      name: '天坛公园',
      type: 'park',
      district: '东城区',
      address: '北京市东城区天坛内东里7号',
      latitude: 39.8822,
      longitude: 116.4066,
      rating: 4.7,
      description: '明清两代帝王祭天的场所，祈年殿是北京的标志建筑之一。',
      priceLevel: 1,
      openTime: '06:00',
      closeTime: '21:00',
      avgVisitMins: 150,
      childFriendly: true,
      dietFriendly: false,
      tags: '公园,皇家,祭天,祈年殿,古建筑,世界遗产',
      imageUrl: '',
      capacity: 10000,
      currentLoad: 45,
      phone: '010-67022617',
    },
    {
      name: '北海公园',
      type: 'park',
      district: '西城区',
      address: '北京市西城区文津街1号',
      latitude: 39.9250,
      longitude: 116.3890,
      rating: 4.5,
      description: '中国现存最古老的皇家园林之一，白塔矗立于琼华岛上，景色优美。',
      priceLevel: 1,
      openTime: '06:00',
      closeTime: '21:00',
      avgVisitMins: 120,
      childFriendly: true,
      dietFriendly: false,
      tags: '公园,皇家园林,白塔,划船,古建筑',
      imageUrl: '',
      capacity: 8000,
      currentLoad: 40,
      phone: '010-64033225',
    },
    {
      name: '玉渊潭公园',
      type: 'park',
      district: '海淀区',
      address: '北京市海淀区西三环中路10号',
      latitude: 39.9146,
      longitude: 116.3298,
      rating: 4.2,
      description: '以樱花闻名的城市公园，每年春季樱花节是北京最美花事之一。',
      priceLevel: 1,
      openTime: '06:00',
      closeTime: '20:30',
      avgVisitMins: 120,
      childFriendly: true,
      dietFriendly: false,
      tags: '公园,樱花,划船,赏花,亲子',
      imageUrl: '',
      capacity: 7000,
      currentLoad: 50,
      phone: '010-88653800',
    },
    {
      name: '日坛公园',
      type: 'park',
      district: '朝阳区',
      address: '北京市朝阳区日坛北路6号',
      latitude: 39.9178,
      longitude: 116.4461,
      rating: 4.0,
      description: '明清两代帝王祭祀大明之神的场所，环境清幽，古木参天。',
      priceLevel: 1,
      openTime: '06:00',
      closeTime: '21:00',
      avgVisitMins: 90,
      childFriendly: true,
      dietFriendly: false,
      tags: '公园,祭祀,古建筑,散步,晨练',
      imageUrl: '',
      capacity: 3000,
      currentLoad: 25,
      phone: '010-85616301',
    },
    {
      name: '紫竹院公园',
      type: 'park',
      district: '海淀区',
      address: '北京市海淀区中关村南大街35号',
      latitude: 39.9438,
      longitude: 116.3227,
      rating: 4.1,
      description: '以竹景取胜的公园，园内种植了大量紫竹，环境清幽雅致。',
      priceLevel: 1,
      openTime: '06:00',
      closeTime: '21:00',
      avgVisitMins: 90,
      childFriendly: true,
      dietFriendly: false,
      tags: '公园,竹林,划船,散步,亲子',
      imageUrl: '',
      capacity: 4000,
      currentLoad: 30,
      phone: '010-68425851',
    },

    // ── Playgrounds (儿童乐园) ───────────────────────────────────────────────
    {
      name: '蓝可可亲子乐园',
      type: 'playground',
      district: '朝阳区',
      address: '北京市朝阳区望京西路50号',
      latitude: 39.9876,
      longitude: 116.4732,
      rating: 4.4,
      description: '大型室内亲子乐园，拥有海洋球池、蹦床、滑梯等多种游乐设施。',
      priceLevel: 2,
      openTime: '09:30',
      closeTime: '20:00',
      avgVisitMins: 180,
      childFriendly: true,
      dietFriendly: false,
      tags: '亲子,儿童乐园,室内,蹦床,海洋球',
      imageUrl: '',
      capacity: 500,
      currentLoad: 65,
      phone: '010-84722666',
    },
    {
      name: '宝燕乐园',
      type: 'playground',
      district: '丰台区',
      address: '北京市丰台区丰管路16号',
      latitude: 39.8581,
      longitude: 116.2881,
      rating: 4.2,
      description: '集水上乐园和室内游乐于一体的亲子娱乐中心，四季皆宜。',
      priceLevel: 2,
      openTime: '10:00',
      closeTime: '20:00',
      avgVisitMins: 180,
      childFriendly: true,
      dietFriendly: false,
      tags: '亲子,儿童乐园,水上乐园,室内游乐',
      imageUrl: '',
      capacity: 600,
      currentLoad: 55,
      phone: '010-63836668',
    },
    {
      name: '蜜芽乐园',
      type: 'playground',
      district: '大兴区',
      address: '北京市大兴区亦庄经济开发区文化园西路',
      latitude: 39.7950,
      longitude: 116.5050,
      rating: 4.3,
      description: '为0-12岁儿童打造的成长乐园，寓教于乐，项目丰富。',
      priceLevel: 2,
      openTime: '09:30',
      closeTime: '19:30',
      avgVisitMins: 150,
      childFriendly: true,
      dietFriendly: false,
      tags: '亲子,儿童乐园,早教,室内游乐',
      imageUrl: '',
      capacity: 400,
      currentLoad: 45,
      phone: '010-57266888',
    },
    {
      name: '奇乐儿儿童乐园',
      type: 'playground',
      district: '海淀区',
      address: '北京市海淀区远大路1号金源时代购物中心',
      latitude: 39.9600,
      longitude: 116.2860,
      rating: 4.1,
      description: '位于金源购物中心内的大型儿童乐园，设施新颖，安全卫生。',
      priceLevel: 2,
      openTime: '10:00',
      closeTime: '21:00',
      avgVisitMins: 120,
      childFriendly: true,
      dietFriendly: false,
      tags: '亲子,儿童乐园,购物中心,室内游乐',
      imageUrl: '',
      capacity: 350,
      currentLoad: 50,
      phone: '010-88871234',
    },

    // ── Malls (购物中心) ─────────────────────────────────────────────────────
    {
      name: 'SKP',
      type: 'mall',
      district: '朝阳区',
      address: '北京市朝阳区建国路87号',
      latitude: 39.9080,
      longitude: 116.4610,
      rating: 4.6,
      description: '全球销售额最高的奢侈品百货商场，汇聚国际顶级品牌。',
      priceLevel: 3,
      openTime: '10:00',
      closeTime: '22:00',
      avgVisitMins: 180,
      childFriendly: false,
      dietFriendly: false,
      tags: '购物中心,奢侈品,国际品牌,高端',
      imageUrl: '',
      capacity: 5000,
      currentLoad: 60,
      phone: '010-85801288',
    },
    {
      name: '合生汇',
      type: 'mall',
      district: '朝阳区',
      address: '北京市朝阳区西大望路甲22号',
      latitude: 39.9006,
      longitude: 116.4650,
      rating: 4.4,
      description: '北京最潮的购物中心之一，地下美食街和网红打卡地汇聚。',
      priceLevel: 2,
      openTime: '10:00',
      closeTime: '22:00',
      avgVisitMins: 180,
      childFriendly: true,
      dietFriendly: false,
      tags: '购物中心,美食,网红打卡,潮牌',
      imageUrl: '',
      capacity: 6000,
      currentLoad: 70,
      phone: '010-87658888',
    },
    {
      name: '三里屯太古里',
      type: 'mall',
      district: '朝阳区',
      address: '北京市朝阳区三里屯路19号',
      latitude: 39.9340,
      longitude: 116.4540,
      rating: 4.5,
      description: '北京最时尚的潮流地标，国际品牌与设计师品牌齐聚。',
      priceLevel: 3,
      openTime: '10:00',
      closeTime: '22:00',
      avgVisitMins: 150,
      childFriendly: false,
      dietFriendly: false,
      tags: '购物中心,时尚,潮流,国际品牌,酒吧街',
      imageUrl: '',
      capacity: 5000,
      currentLoad: 65,
      phone: '010-64176688',
    },
    {
      name: '西单大悦城',
      type: 'mall',
      district: '西城区',
      address: '北京市西城区西单北大街131号',
      latitude: 39.9118,
      longitude: 116.3738,
      rating: 4.3,
      description: '年轻人最爱的购物天堂，汇集众多潮流品牌和美食餐厅。',
      priceLevel: 2,
      openTime: '10:00',
      closeTime: '22:00',
      avgVisitMins: 150,
      childFriendly: true,
      dietFriendly: false,
      tags: '购物中心,潮流,年轻人,美食',
      imageUrl: '',
      capacity: 5000,
      currentLoad: 72,
      phone: '010-66518899',
    },
    {
      name: '颐堤港',
      type: 'mall',
      district: '朝阳区',
      address: '北京市朝阳区酒仙桥路18号',
      latitude: 39.9790,
      longitude: 116.4910,
      rating: 4.4,
      description: '紧邻798艺术区的品质购物中心，环境优雅，品牌丰富。',
      priceLevel: 2,
      openTime: '10:00',
      closeTime: '22:00',
      avgVisitMins: 150,
      childFriendly: true,
      dietFriendly: false,
      tags: '购物中心,品质生活,798,亲子',
      imageUrl: '',
      capacity: 4000,
      currentLoad: 45,
      phone: '010-84260808',
    },
    {
      name: '蓝色港湾',
      type: 'mall',
      district: '朝阳区',
      address: '北京市朝阳区朝阳公园路6号',
      latitude: 39.9360,
      longitude: 116.4710,
      rating: 4.3,
      description: '湖畔开放式购物区，融合购物、餐饮与娱乐，夜景迷人。',
      priceLevel: 2,
      openTime: '10:00',
      closeTime: '22:00',
      avgVisitMins: 180,
      childFriendly: true,
      dietFriendly: false,
      tags: '购物中心,湖畔,夜景,亲子,美食',
      imageUrl: '',
      capacity: 5000,
      currentLoad: 55,
      phone: '010-59056688',
    },
    {
      name: '朝阳大悦城',
      type: 'mall',
      district: '朝阳区',
      address: '北京市朝阳区朝阳北路101号',
      latitude: 39.9220,
      longitude: 116.5170,
      rating: 4.3,
      description: '超大体量的购物中心，集购物、餐饮、娱乐于一体。',
      priceLevel: 2,
      openTime: '10:00',
      closeTime: '22:00',
      avgVisitMins: 180,
      childFriendly: true,
      dietFriendly: false,
      tags: '购物中心,美食,娱乐,亲子',
      imageUrl: '',
      capacity: 6000,
      currentLoad: 60,
      phone: '010-85522200',
    },

    // ── Cinemas (电影院) ─────────────────────────────────────────────────────
    {
      name: '万达影城(CBD店)',
      type: 'cinema',
      district: '朝阳区',
      address: '北京市朝阳区建国路93号万达广场',
      latitude: 39.9085,
      longitude: 116.4605,
      rating: 4.3,
      description: '位于CBD核心区的IMAX影院，观影体验一流。',
      priceLevel: 2,
      openTime: '09:30',
      closeTime: '23:30',
      avgVisitMins: 150,
      childFriendly: true,
      dietFriendly: false,
      tags: '电影院,IMAX,3D,万达',
      imageUrl: '',
      capacity: 800,
      currentLoad: 45,
      phone: '010-59604888',
    },
    {
      name: 'CGV影城(颐堤港店)',
      type: 'cinema',
      district: '朝阳区',
      address: '北京市朝阳区酒仙桥路18号颐堤港',
      latitude: 39.9792,
      longitude: 116.4912,
      rating: 4.4,
      description: '韩系高端影院品牌，座椅舒适，银幕效果出色。',
      priceLevel: 2,
      openTime: '09:30',
      closeTime: '23:30',
      avgVisitMins: 150,
      childFriendly: true,
      dietFriendly: false,
      tags: '电影院,4DX,IMAX,韩系',
      imageUrl: '',
      capacity: 600,
      currentLoad: 40,
      phone: '010-84260868',
    },
    {
      name: '金逸影城(大钟寺店)',
      type: 'cinema',
      district: '海淀区',
      address: '北京市海淀区北三环西路23号',
      latitude: 39.9575,
      longitude: 116.3510,
      rating: 4.1,
      description: '大型多厅影院，价格亲民，片源丰富。',
      priceLevel: 1,
      openTime: '09:00',
      closeTime: '23:00',
      avgVisitMins: 150,
      childFriendly: true,
      dietFriendly: false,
      tags: '电影院,实惠,多厅',
      imageUrl: '',
      capacity: 700,
      currentLoad: 35,
      phone: '010-62126688',
    },
    {
      name: '英皇电影城',
      type: 'cinema',
      district: '东城区',
      address: '北京市东城区东长安街1号东方广场',
      latitude: 39.9138,
      longitude: 116.4118,
      rating: 4.5,
      description: '位于王府井核心的高端影院，豪华座椅与顶级音效。',
      priceLevel: 3,
      openTime: '10:00',
      closeTime: '23:30',
      avgVisitMins: 150,
      childFriendly: true,
      dietFriendly: false,
      tags: '电影院,高端,豪华,王府井',
      imageUrl: '',
      capacity: 500,
      currentLoad: 50,
      phone: '010-85151234',
    },

    // ── Museums (博物馆) ─────────────────────────────────────────────────────
    {
      name: '故宫博物院',
      type: 'museum',
      district: '东城区',
      address: '北京市东城区景山前街4号',
      latitude: 39.9163,
      longitude: 116.3972,
      rating: 4.9,
      description: '中国最大的古代文化艺术博物馆，世界五大宫殿之一，藏品百万余件。',
      priceLevel: 2,
      openTime: '08:30',
      closeTime: '17:00',
      avgVisitMins: 300,
      childFriendly: true,
      dietFriendly: false,
      tags: '博物馆,故宫,紫禁城,世界遗产,古建筑',
      imageUrl: '',
      capacity: 30000,
      currentLoad: 78,
      phone: '010-85007114',
    },
    {
      name: '国家博物馆',
      type: 'museum',
      district: '东城区',
      address: '北京市东城区东长安街16号',
      latitude: 39.9045,
      longitude: 116.4070,
      rating: 4.8,
      description: '世界上单体建筑面积最大的博物馆，收藏中华文明五千年精华。',
      priceLevel: 1,
      openTime: '09:00',
      closeTime: '17:00',
      avgVisitMins: 240,
      childFriendly: true,
      dietFriendly: false,
      tags: '博物馆,国家,历史,文物,免费',
      imageUrl: '',
      capacity: 20000,
      currentLoad: 70,
      phone: '010-65116400',
    },
    {
      name: '首都博物馆',
      type: 'museum',
      district: '西城区',
      address: '北京市西城区复兴门外大街16号',
      latitude: 39.9058,
      longitude: 116.3418,
      rating: 4.5,
      description: '展示北京三千年建城史和八百年建都史的综合博物馆。',
      priceLevel: 1,
      openTime: '09:00',
      closeTime: '17:00',
      avgVisitMins: 180,
      childFriendly: true,
      dietFriendly: false,
      tags: '博物馆,北京历史,免费,文化',
      imageUrl: '',
      capacity: 8000,
      currentLoad: 40,
      phone: '010-63370491',
    },
    {
      name: '中国科技馆',
      type: 'museum',
      district: '朝阳区',
      address: '北京市朝阳区北辰东路5号',
      latitude: 39.9940,
      longitude: 116.3980,
      rating: 4.6,
      description: '国内唯一的国家级综合性科技馆，互动体验项目丰富，适合亲子科普。',
      priceLevel: 1,
      openTime: '09:30',
      closeTime: '17:00',
      avgVisitMins: 240,
      childFriendly: true,
      dietFriendly: false,
      tags: '博物馆,科技,互动,亲子,科普,IMAX',
      imageUrl: '',
      capacity: 10000,
      currentLoad: 55,
      phone: '010-59041000',
    },

    // ── Galleries (美术馆) ────────────────────────────────────────────────────
    {
      name: '798艺术区',
      type: 'gallery',
      district: '朝阳区',
      address: '北京市朝阳区酒仙桥路2号',
      latitude: 39.9840,
      longitude: 116.4940,
      rating: 4.5,
      description: '北京最具代表性的当代艺术区，汇聚画廊、工作室和创意空间。',
      priceLevel: 1,
      openTime: '10:00',
      closeTime: '18:00',
      avgVisitMins: 180,
      childFriendly: false,
      dietFriendly: false,
      tags: '美术馆,当代艺术,画廊,创意,打卡',
      imageUrl: '',
      capacity: 5000,
      currentLoad: 50,
      phone: '',
    },
    {
      name: '今日美术馆',
      type: 'gallery',
      district: '朝阳区',
      address: '北京市朝阳区百子湾路32号',
      latitude: 39.8980,
      longitude: 116.4700,
      rating: 4.3,
      description: '中国第一家民营非企业公益性美术馆，专注当代艺术。',
      priceLevel: 1,
      openTime: '10:00',
      closeTime: '18:00',
      avgVisitMins: 120,
      childFriendly: false,
      dietFriendly: false,
      tags: '美术馆,当代艺术,民营,展览',
      imageUrl: '',
      capacity: 800,
      currentLoad: 30,
      phone: '010-58760600',
    },
    {
      name: '中国美术馆',
      type: 'gallery',
      district: '东城区',
      address: '北京市东城区五四大街1号',
      latitude: 39.9250,
      longitude: 116.4050,
      rating: 4.4,
      description: '国家造型艺术博物馆，收藏近现代美术作品十余万件。',
      priceLevel: 1,
      openTime: '09:00',
      closeTime: '17:00',
      avgVisitMins: 120,
      childFriendly: false,
      dietFriendly: false,
      tags: '美术馆,国家级,近现代美术,免费',
      imageUrl: '',
      capacity: 2000,
      currentLoad: 35,
      phone: '010-64001476',
    },
    {
      name: '松美术馆',
      type: 'gallery',
      district: '顺义区',
      address: '北京市顺义区天竺镇格拉斯路',
      latitude: 40.0500,
      longitude: 116.5700,
      rating: 4.6,
      description: '松艺术区核心美术馆，以东方美学为基调的私人美术馆。',
      priceLevel: 2,
      openTime: '10:00',
      closeTime: '18:00',
      avgVisitMins: 120,
      childFriendly: false,
      dietFriendly: false,
      tags: '美术馆,东方美学,私人,当代艺术',
      imageUrl: '',
      capacity: 500,
      currentLoad: 25,
      phone: '010-80426888',
    },

    // ── Aquariums (水族馆) ───────────────────────────────────────────────────
    {
      name: '富国海底世界',
      type: 'aquarium',
      district: '朝阳区',
      address: '北京市朝阳区工人体育场南门',
      latitude: 39.9290,
      longitude: 116.4440,
      rating: 4.2,
      description: '北京最早的海洋馆之一，拥有120米亚克力海底隧道。',
      priceLevel: 2,
      openTime: '09:00',
      closeTime: '18:00',
      avgVisitMins: 120,
      childFriendly: true,
      dietFriendly: false,
      tags: '水族馆,海底隧道,亲子,海洋动物',
      imageUrl: '',
      capacity: 1500,
      currentLoad: 55,
      phone: '010-65913397',
    },
    {
      name: '太平洋海底世界',
      type: 'aquarium',
      district: '海淀区',
      address: '北京市海淀区西三环中路11号中央电视塔下',
      latitude: 39.9168,
      longitude: 116.3172,
      rating: 4.1,
      description: '位于中央电视塔下的海洋馆，企鹅馆是最大亮点。',
      priceLevel: 2,
      openTime: '09:00',
      closeTime: '17:30',
      avgVisitMins: 120,
      childFriendly: true,
      dietFriendly: false,
      tags: '水族馆,企鹅,亲子,海底隧道',
      imageUrl: '',
      capacity: 1200,
      currentLoad: 45,
      phone: '010-68461172',
    },

    // ── Zoos (动物园) ────────────────────────────────────────────────────────
    {
      name: '北京动物园',
      type: 'zoo',
      district: '西城区',
      address: '北京市西城区西直门外大街137号',
      latitude: 39.9400,
      longitude: 116.3360,
      rating: 4.3,
      description: '中国开放最早、品种最多的动物园，大熊猫馆最受欢迎。',
      priceLevel: 1,
      openTime: '07:30',
      closeTime: '18:00',
      avgVisitMins: 240,
      childFriendly: true,
      dietFriendly: false,
      tags: '动物园,大熊猫,亲子,科普',
      imageUrl: '',
      capacity: 20000,
      currentLoad: 60,
      phone: '010-68314411',
    },
    {
      name: '北京野生动物园',
      type: 'zoo',
      district: '大兴区',
      address: '北京市大兴区榆垡镇万亩森林',
      latitude: 39.5600,
      longitude: 116.3300,
      rating: 4.4,
      description: '大型自然生态野生动物园，可自驾穿越猛兽区。',
      priceLevel: 2,
      openTime: '08:30',
      closeTime: '17:30',
      avgVisitMins: 300,
      childFriendly: true,
      dietFriendly: false,
      tags: '动物园,野生动物,自驾,亲子',
      imageUrl: '',
      capacity: 15000,
      currentLoad: 45,
      phone: '010-89216666',
    },

    // ── Night Markets (夜市) ─────────────────────────────────────────────────
    {
      name: '簋街',
      type: 'night_market',
      district: '东城区',
      address: '北京市东城区东直门内大街',
      latitude: 39.9410,
      longitude: 116.4270,
      rating: 4.4,
      description: '北京最著名的美食夜市街，以麻辣小龙虾闻名，灯火通明至深夜。',
      priceLevel: 2,
      openTime: '17:00',
      closeTime: '03:00',
      avgVisitMins: 120,
      childFriendly: false,
      dietFriendly: false,
      tags: '夜市,小吃,小龙虾,深夜食堂,麻辣',
      imageUrl: '',
      capacity: 3000,
      currentLoad: 75,
      phone: '',
    },
    {
      name: '王府井夜市',
      type: 'night_market',
      district: '东城区',
      address: '北京市东城区王府井大街',
      latitude: 39.9140,
      longitude: 116.4100,
      rating: 3.9,
      description: '北京最知名的商业步行街，夜市小吃品种繁多，游客必到之处。',
      priceLevel: 2,
      openTime: '18:00',
      closeTime: '23:00',
      avgVisitMins: 90,
      childFriendly: true,
      dietFriendly: false,
      tags: '夜市,小吃,旅游,步行街',
      imageUrl: '',
      capacity: 5000,
      currentLoad: 65,
      phone: '',
    },

    // ── Food Streets (美食街) ────────────────────────────────────────────────
    {
      name: '南锣鼓巷',
      type: 'food_street',
      district: '东城区',
      address: '北京市东城区南锣鼓巷',
      latitude: 39.9350,
      longitude: 116.4030,
      rating: 4.2,
      description: '北京最古老的街区之一，胡同文化与美食创意小店交融。',
      priceLevel: 2,
      openTime: '10:00',
      closeTime: '22:00',
      avgVisitMins: 120,
      childFriendly: true,
      dietFriendly: false,
      tags: '美食街,胡同,文创,小吃,打卡',
      imageUrl: '',
      capacity: 4000,
      currentLoad: 70,
      phone: '',
    },
    {
      name: '烟袋斜街',
      type: 'food_street',
      district: '西城区',
      address: '北京市西城区烟袋斜街',
      latitude: 39.9380,
      longitude: 116.3880,
      rating: 4.1,
      description: '什刹海畔的古韵小街，传统小吃与文艺店铺并存。',
      priceLevel: 1,
      openTime: '10:00',
      closeTime: '22:00',
      avgVisitMins: 90,
      childFriendly: true,
      dietFriendly: false,
      tags: '美食街,什刹海,胡同,传统小吃',
      imageUrl: '',
      capacity: 2000,
      currentLoad: 55,
      phone: '',
    },
    {
      name: '牛街',
      type: 'food_street',
      district: '西城区',
      address: '北京市西城区牛街',
      latitude: 39.8930,
      longitude: 116.3560,
      rating: 4.5,
      description: '北京最著名的穆斯林美食街，清真小吃品种丰富地道。',
      priceLevel: 1,
      openTime: '07:00',
      closeTime: '21:00',
      avgVisitMins: 90,
      childFriendly: true,
      dietFriendly: false,
      tags: '美食街,清真,牛羊肉,传统小吃',
      imageUrl: '',
      capacity: 3000,
      currentLoad: 60,
      phone: '',
    },
    {
      name: '护国寺街',
      type: 'food_street',
      district: '西城区',
      address: '北京市西城区护国寺街',
      latitude: 39.9320,
      longitude: 116.3710,
      rating: 4.3,
      description: '北京传统小吃的发源地之一，护国寺小吃店最为知名。',
      priceLevel: 1,
      openTime: '08:00',
      closeTime: '21:00',
      avgVisitMins: 90,
      childFriendly: true,
      dietFriendly: false,
      tags: '美食街,传统小吃,老字号,京味',
      imageUrl: '',
      capacity: 2000,
      currentLoad: 50,
      phone: '',
    },

    // ── Sports (运动场馆) ────────────────────────────────────────────────────
    {
      name: '国家体育场(鸟巢)',
      type: 'sports',
      district: '朝阳区',
      address: '北京市朝阳区国家体育场南路1号',
      latitude: 39.9930,
      longitude: 116.3960,
      rating: 4.6,
      description: '2008年北京奥运会主体育场，可容纳9万观众，建筑奇观。',
      priceLevel: 2,
      openTime: '09:00',
      closeTime: '21:00',
      avgVisitMins: 120,
      childFriendly: true,
      dietFriendly: false,
      tags: '运动场馆,鸟巢,奥运,地标,建筑',
      imageUrl: '',
      capacity: 90000,
      currentLoad: 30,
      phone: '010-84986856',
    },
    {
      name: '水立方',
      type: 'sports',
      district: '朝阳区',
      address: '北京市朝阳区天辰东路11号',
      latitude: 39.9930,
      longitude: 116.3900,
      rating: 4.5,
      description: '国家游泳中心，膜结构建筑世界之最，冬季变身冰立方。',
      priceLevel: 2,
      openTime: '09:00',
      closeTime: '21:00',
      avgVisitMins: 120,
      childFriendly: true,
      dietFriendly: false,
      tags: '运动场馆,游泳,冰壶,奥运,地标',
      imageUrl: '',
      capacity: 6000,
      currentLoad: 45,
      phone: '010-84370088',
    },
    {
      name: '五棵松体育馆',
      type: 'sports',
      district: '海淀区',
      address: '北京市海淀区复兴路69号',
      latitude: 39.9060,
      longitude: 116.2820,
      rating: 4.4,
      description: 'NBA级别篮球馆，CBA北京首钢主场，也是大型演唱会场地。',
      priceLevel: 2,
      openTime: '09:00',
      closeTime: '22:00',
      avgVisitMins: 180,
      childFriendly: true,
      dietFriendly: false,
      tags: '运动场馆,篮球,演唱会,首钢',
      imageUrl: '',
      capacity: 18000,
      currentLoad: 35,
      phone: '010-88226688',
    },
    {
      name: '国家网球中心',
      type: 'sports',
      district: '朝阳区',
      address: '北京市朝阳区林萃路2号',
      latitude: 39.9950,
      longitude: 116.3820,
      rating: 4.3,
      description: '中国网球公开赛举办地，拥有可开合屋顶的莲花球场。',
      priceLevel: 2,
      openTime: '08:00',
      closeTime: '21:00',
      avgVisitMins: 150,
      childFriendly: true,
      dietFriendly: false,
      tags: '运动场馆,网球,中网,赛事',
      imageUrl: '',
      capacity: 15000,
      currentLoad: 25,
      phone: '010-84371166',
    },

    // ── Temples (寺庙) ───────────────────────────────────────────────────────
    {
      name: '雍和宫',
      type: 'temple',
      district: '东城区',
      address: '北京市东城区雍和宫大街12号',
      latitude: 39.9470,
      longitude: 116.4180,
      rating: 4.7,
      description: '北京最大的藏传佛教寺院，香火鼎盛，清雅庄严。',
      priceLevel: 1,
      openTime: '09:00',
      closeTime: '16:30',
      avgVisitMins: 90,
      childFriendly: false,
      dietFriendly: true,
      tags: '寺庙,藏传佛教,祈福,古建筑',
      imageUrl: '',
      capacity: 5000,
      currentLoad: 60,
      phone: '010-64044499',
    },
    {
      name: '白云观',
      type: 'temple',
      district: '西城区',
      address: '北京市西城区白云观街9号',
      latitude: 39.8960,
      longitude: 116.3420,
      rating: 4.3,
      description: '道教全真派祖庭，北京最大的道观，春节庙会热闹非凡。',
      priceLevel: 1,
      openTime: '08:30',
      closeTime: '16:30',
      avgVisitMins: 90,
      childFriendly: false,
      dietFriendly: true,
      tags: '寺庙,道教,庙会,祈福',
      imageUrl: '',
      capacity: 3000,
      currentLoad: 35,
      phone: '010-63463531',
    },
    {
      name: '潭柘寺',
      type: 'temple',
      district: '门头沟区',
      address: '北京市门头沟区潭柘寺镇',
      latitude: 39.8680,
      longitude: 116.0350,
      rating: 4.5,
      description: '北京最古老的寺院，"先有潭柘寺，后有北京城"。',
      priceLevel: 2,
      openTime: '08:00',
      closeTime: '17:00',
      avgVisitMins: 120,
      childFriendly: false,
      dietFriendly: true,
      tags: '寺庙,古刹,祈福,银杏,历史',
      imageUrl: '',
      capacity: 3000,
      currentLoad: 30,
      phone: '010-60861699',
    },
    {
      name: '红螺寺',
      type: 'temple',
      district: '怀柔区',
      address: '北京市怀柔区红螺东路2号',
      latitude: 40.3780,
      longitude: 116.6320,
      rating: 4.4,
      description: '京北第一大寺，"南有普陀，北有红螺"，千年古刹。',
      priceLevel: 2,
      openTime: '08:00',
      closeTime: '17:00',
      avgVisitMins: 150,
      childFriendly: false,
      dietFriendly: true,
      tags: '寺庙,古刹,祈福,登山',
      imageUrl: '',
      capacity: 5000,
      currentLoad: 28,
      phone: '010-60681175',
    },

    // ── Additional venues for more district coverage ─────────────────────────
    {
      name: '圆明园遗址公园',
      type: 'park',
      district: '海淀区',
      address: '北京市海淀区清华西路28号',
      latitude: 40.0090,
      longitude: 116.2980,
      rating: 4.5,
      description: '曾经的万园之园，如今遗址警醒后人，西洋楼遗迹震撼人心。',
      priceLevel: 1,
      openTime: '07:00',
      closeTime: '19:00',
      avgVisitMins: 180,
      childFriendly: true,
      dietFriendly: false,
      tags: '公园,遗址,历史,爱国教育',
      imageUrl: '',
      capacity: 12000,
      currentLoad: 50,
      phone: '010-62543673',
    },
    {
      name: '景山公园',
      type: 'park',
      district: '西城区',
      address: '北京市西城区景山前街',
      latitude: 39.9220,
      longitude: 116.3960,
      rating: 4.4,
      description: '可俯瞰故宫全景的皇家园林，万春亭是北京城中轴线的制高点。',
      priceLevel: 1,
      openTime: '06:30',
      closeTime: '20:00',
      avgVisitMins: 90,
      childFriendly: true,
      dietFriendly: false,
      tags: '公园,皇家,俯瞰故宫,中轴线,牡丹',
      imageUrl: '',
      capacity: 5000,
      currentLoad: 40,
      phone: '010-64038098',
    },
    {
      name: '北京欢乐谷',
      type: 'playground',
      district: '朝阳区',
      address: '北京市朝阳区东四环小武基北路',
      latitude: 39.8630,
      longitude: 116.4950,
      rating: 4.3,
      description: '北京最大的主题公园，刺激过山车与水上项目应有尽有。',
      priceLevel: 2,
      openTime: '09:00',
      closeTime: '22:00',
      avgVisitMins: 360,
      childFriendly: true,
      dietFriendly: false,
      tags: '主题公园,过山车,水上乐园,亲子',
      imageUrl: '',
      capacity: 30000,
      currentLoad: 70,
      phone: '010-67389898',
    },
    {
      name: '石景山游乐园',
      type: 'playground',
      district: '石景山区',
      address: '北京市石景山区石景山路25号',
      latitude: 39.9060,
      longitude: 116.2220,
      rating: 4.0,
      description: '北京老牌游乐园，摩天轮是石景山区的地标。',
      priceLevel: 2,
      openTime: '09:00',
      closeTime: '21:00',
      avgVisitMins: 240,
      childFriendly: true,
      dietFriendly: false,
      tags: '游乐园,摩天轮,亲子,经典',
      imageUrl: '',
      capacity: 15000,
      currentLoad: 45,
      phone: '010-68862547',
    },
    {
      name: '大运河博物馆',
      type: 'museum',
      district: '通州区',
      address: '北京市通州区绿心路1号',
      latitude: 39.8970,
      longitude: 116.6700,
      rating: 4.5,
      description: '首都博物馆东馆，展示大运河文化与北京城市发展。',
      priceLevel: 1,
      openTime: '09:00',
      closeTime: '17:00',
      avgVisitMins: 180,
      childFriendly: true,
      dietFriendly: false,
      tags: '博物馆,大运河,文化,免费',
      imageUrl: '',
      capacity: 5000,
      currentLoad: 35,
      phone: '010-60950666',
    },
    {
      name: '中国航空博物馆',
      type: 'museum',
      district: '昌平区',
      address: '北京市昌平区小汤山镇',
      latitude: 40.1600,
      longitude: 116.3900,
      rating: 4.3,
      description: '亚洲最大的航空博物馆，收藏各型飞机数百架。',
      priceLevel: 1,
      openTime: '08:30',
      closeTime: '17:00',
      avgVisitMins: 150,
      childFriendly: true,
      dietFriendly: false,
      tags: '博物馆,航空,军事,飞机,亲子',
      imageUrl: '',
      capacity: 5000,
      currentLoad: 30,
      phone: '010-61784882',
    },
  ];

  const venues: Awaited<ReturnType<typeof db.venue.create>>[] = [];
  for (const v of venueData) {
    const venue = await db.venue.create({ data: v });
    venues.push(venue);
  }
  console.log(`Created ${venues.length} venues`);

  // ─── Seed Restaurants (40+ entries) ────────────────────────────────────────
  console.log('Seeding restaurants...');

  const restaurantData = [
    // ── Chinese (中餐) ───────────────────────────────────────────────────────
    {
      name: '全聚德(前门店)',
      cuisineType: 'chinese',
      district: '东城区',
      address: '北京市东城区前门大街30号',
      latitude: 39.8980,
      longitude: 116.3980,
      rating: 4.2,
      description: '百年老字号，北京烤鸭的代名词，前门店为原址老店。',
      priceLevel: 3,
      avgPricePerPerson: 200,
      openTime: '11:00',
      closeTime: '21:30',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '中餐,烤鸭,老字号,京味',
      imageUrl: '',
      totalSeats: 300,
      currentWaitMins: 30,
      availableSlots: '11:00,11:30,12:00,12:30,17:00,17:30,18:00,18:30,19:00',
      phone: '010-67011379',
    },
    {
      name: '大董(工体店)',
      cuisineType: 'chinese',
      district: '朝阳区',
      address: '北京市朝阳区工人体育场东路工体东路2号',
      latitude: 39.9290,
      longitude: 116.4480,
      rating: 4.6,
      description: '新派烤鸭代表，酥不腻烤鸭入口即化，意境菜开创者。',
      priceLevel: 3,
      avgPricePerPerson: 350,
      openTime: '11:00',
      closeTime: '22:00',
      childFriendly: false,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '中餐,烤鸭,意境菜,高端',
      imageUrl: '',
      totalSeats: 200,
      currentWaitMins: 45,
      availableSlots: '11:30,12:00,17:30,18:00,18:30',
      phone: '010-65860003',
    },
    {
      name: '局气(西单店)',
      cuisineType: 'chinese',
      district: '西城区',
      address: '北京市西城区西单北大街120号',
      latitude: 39.9130,
      longitude: 116.3740,
      rating: 4.3,
      description: '地道京味菜馆，装修复古怀旧，蜂窝煤炒饭是招牌。',
      priceLevel: 2,
      avgPricePerPerson: 110,
      openTime: '11:00',
      closeTime: '21:30',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '中餐,京味菜,怀旧,蜂窝煤炒饭',
      imageUrl: '',
      totalSeats: 150,
      currentWaitMins: 20,
      availableSlots: '11:00,11:30,12:00,17:00,17:30,18:00,18:30,19:00',
      phone: '010-66006688',
    },
    {
      name: '花家怡园(望京店)',
      cuisineType: 'chinese',
      district: '朝阳区',
      address: '北京市朝阳区望京西路50号',
      latitude: 39.9880,
      longitude: 116.4730,
      rating: 4.2,
      description: '京味融合菜的代表餐厅，环境古色古香，菜品精致。',
      priceLevel: 2,
      avgPricePerPerson: 130,
      openTime: '11:00',
      closeTime: '21:30',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '中餐,京味,融合菜,商务宴请',
      imageUrl: '',
      totalSeats: 180,
      currentWaitMins: 15,
      availableSlots: '11:00,11:30,12:00,12:30,17:00,17:30,18:00,18:30,19:00',
      phone: '010-64736888',
    },
    {
      name: '四季民福(故宫店)',
      cuisineType: 'chinese',
      district: '东城区',
      address: '北京市东城区南池子大街11号',
      latitude: 39.9135,
      longitude: 116.4010,
      rating: 4.5,
      description: '近年最火的北京烤鸭店，故宫店可边吃烤鸭边赏角楼。',
      priceLevel: 2,
      avgPricePerPerson: 160,
      openTime: '10:30',
      closeTime: '22:00',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '中餐,烤鸭,故宫,网红,排队',
      imageUrl: '',
      totalSeats: 200,
      currentWaitMins: 60,
      availableSlots: '11:00,14:00,17:00',
      phone: '010-65288558',
    },

    // ── Japanese (日料) ──────────────────────────────────────────────────────
    {
      name: '将太无二(CBD店)',
      cuisineType: 'japanese',
      district: '朝阳区',
      address: '北京市朝阳区东三环中路39号建外SOHO',
      latitude: 39.9070,
      longitude: 116.4560,
      rating: 4.3,
      description: '创意日料品牌，融合中西元素，寿司卷是招牌。',
      priceLevel: 2,
      avgPricePerPerson: 150,
      openTime: '11:00',
      closeTime: '22:00',
      childFriendly: false,
      dietFriendly: false,
      hasPrivateRoom: false,
      tags: '日料,创意寿司,刺身,商务套餐',
      imageUrl: '',
      totalSeats: 100,
      currentWaitMins: 15,
      availableSlots: '11:00,11:30,12:00,17:30,18:00,18:30,19:00',
      phone: '010-58691234',
    },
    {
      name: '鮨一',
      cuisineType: 'japanese',
      district: '朝阳区',
      address: '北京市朝阳区新源街1号',
      latitude: 39.9510,
      longitude: 116.4610,
      rating: 4.7,
      description: '高端日式Omakase，精选当季食材，师傅现场手作。',
      priceLevel: 3,
      avgPricePerPerson: 480,
      openTime: '11:30',
      closeTime: '22:00',
      childFriendly: false,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '日料,Omakase,高端,寿司,匠人',
      imageUrl: '',
      totalSeats: 30,
      currentWaitMins: 0,
      availableSlots: '12:00,18:00,18:30',
      phone: '010-64608866',
    },
    {
      name: '村上一屋(中关村店)',
      cuisineType: 'japanese',
      district: '海淀区',
      address: '北京市海淀区中关村大街15号',
      latitude: 39.9810,
      longitude: 116.3170,
      rating: 4.1,
      description: '平价日料连锁，鳗鱼饭和拉面性价比极高。',
      priceLevel: 1,
      avgPricePerPerson: 60,
      openTime: '10:30',
      closeTime: '21:30',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: false,
      tags: '日料,平价,鳗鱼饭,拉面,学生',
      imageUrl: '',
      totalSeats: 80,
      currentWaitMins: 10,
      availableSlots: '11:00,11:30,12:00,12:30,17:00,17:30,18:00,18:30,19:00,19:30',
      phone: '010-82668888',
    },
    {
      name: '道顿堀',
      cuisineType: 'japanese',
      district: '西城区',
      address: '北京市西城区金融街甲15号',
      latitude: 39.9130,
      longitude: 116.3570,
      rating: 4.4,
      description: '正宗大阪风味，铁板烧与大阪烧是特色。',
      priceLevel: 2,
      avgPricePerPerson: 130,
      openTime: '11:00',
      closeTime: '22:00',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '日料,大阪烧,铁板烧,居酒屋',
      imageUrl: '',
      totalSeats: 90,
      currentWaitMins: 20,
      availableSlots: '11:00,11:30,12:00,17:30,18:00,18:30,19:00',
      phone: '010-66228866',
    },

    // ── Western (西餐) ───────────────────────────────────────────────────────
    {
      name: 'TRB Hutong',
      cuisineType: 'western',
      district: '东城区',
      address: '北京市东城区沙滩北街23号',
      latitude: 39.9250,
      longitude: 116.4050,
      rating: 4.8,
      description: '藏身于600年古寺内的法式餐厅，米其林级别，极具仪式感。',
      priceLevel: 3,
      avgPricePerPerson: 500,
      openTime: '11:30',
      closeTime: '22:00',
      childFriendly: false,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '西餐,法餐,米其林,古寺,约会',
      imageUrl: '',
      totalSeats: 60,
      currentWaitMins: 0,
      availableSlots: '12:00,18:00,18:30',
      phone: '010-84002232',
    },
    {
      name: "MORTON'S牛排馆",
      cuisineType: 'western',
      district: '朝阳区',
      address: '北京市朝阳区东三环北路金桐西路10号',
      latitude: 39.9080,
      longitude: 116.4550,
      rating: 4.5,
      description: '美国顶级牛排馆北京分店，USDA Prime级别牛排。',
      priceLevel: 3,
      avgPricePerPerson: 450,
      openTime: '11:30',
      closeTime: '22:30',
      childFriendly: false,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '西餐,牛排,高端,商务宴请',
      imageUrl: '',
      totalSeats: 120,
      currentWaitMins: 10,
      availableSlots: '11:30,12:00,17:30,18:00,18:30,19:00',
      phone: '010-59608888',
    },
    {
      name: '福楼',
      cuisineType: 'western',
      district: '朝阳区',
      address: '北京市朝阳区东三环北路16号',
      latitude: 39.9300,
      longitude: 116.4600,
      rating: 4.4,
      description: '经典法式餐厅，鹅肝和蜗牛是招牌，环境优雅浪漫。',
      priceLevel: 3,
      avgPricePerPerson: 380,
      openTime: '11:30',
      closeTime: '22:00',
      childFriendly: false,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '西餐,法餐,鹅肝,蜗牛,浪漫',
      imageUrl: '',
      totalSeats: 100,
      currentWaitMins: 15,
      availableSlots: '12:00,12:30,18:00,18:30,19:00',
      phone: '010-65955139',
    },
    {
      name: 'The Cut',
      cuisineType: 'western',
      district: '朝阳区',
      address: '北京市朝阳区三里屯路19号太古里南区',
      latitude: 39.9340,
      longitude: 116.4530,
      rating: 4.3,
      description: '三里屯精品牛排馆，干式熟成牛排为特色。',
      priceLevel: 3,
      avgPricePerPerson: 350,
      openTime: '11:30',
      closeTime: '23:00',
      childFriendly: false,
      dietFriendly: false,
      hasPrivateRoom: false,
      tags: '西餐,牛排,干式熟成,三里屯',
      imageUrl: '',
      totalSeats: 80,
      currentWaitMins: 25,
      availableSlots: '12:00,12:30,18:00,18:30,19:00,19:30',
      phone: '010-64178888',
    },

    // ── Hotpot (火锅) ────────────────────────────────────────────────────────
    {
      name: '海底捞(三里屯店)',
      cuisineType: 'hotpot',
      district: '朝阳区',
      address: '北京市朝阳区三里屯路19号太古里',
      latitude: 39.9330,
      longitude: 116.4530,
      rating: 4.5,
      description: '以极致服务闻名的火锅连锁，等位免费美甲和小吃。',
      priceLevel: 2,
      avgPricePerPerson: 120,
      openTime: '10:00',
      closeTime: '07:00',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '火锅,川味,服务好,深夜食堂,捞面表演',
      imageUrl: '',
      totalSeats: 300,
      currentWaitMins: 30,
      availableSlots: '11:00,11:30,12:00,12:30,17:00,17:30,18:00,18:30,19:00,19:30,20:00',
      phone: '010-64170808',
    },
    {
      name: '呷哺呷哺(西直门店)',
      cuisineType: 'hotpot',
      district: '西城区',
      address: '北京市西城区西直门外大街1号嘉茂购物中心',
      latitude: 39.9410,
      longitude: 116.3480,
      rating: 4.0,
      description: '一人一锅的小火锅，经济实惠，快捷方便。',
      priceLevel: 1,
      avgPricePerPerson: 55,
      openTime: '10:30',
      closeTime: '22:00',
      childFriendly: true,
      dietFriendly: true,
      hasPrivateRoom: false,
      tags: '火锅,一人锅,实惠,快捷',
      imageUrl: '',
      totalSeats: 100,
      currentWaitMins: 5,
      availableSlots: '11:00,11:30,12:00,12:30,13:00,17:00,17:30,18:00,18:30,19:00,19:30',
      phone: '010-58301234',
    },
    {
      name: '巴奴毛肚火锅(国贸店)',
      cuisineType: 'hotpot',
      district: '朝阳区',
      address: '北京市朝阳区建国门外大街1号国贸商城',
      latitude: 39.9085,
      longitude: 116.4550,
      rating: 4.5,
      description: '以毛肚为招牌的川味火锅，菌汤锅底鲜美，菜品品质出众。',
      priceLevel: 2,
      avgPricePerPerson: 140,
      openTime: '11:00',
      closeTime: '22:00',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '火锅,毛肚,菌汤,川味,品质',
      imageUrl: '',
      totalSeats: 200,
      currentWaitMins: 40,
      availableSlots: '11:00,11:30,12:00,17:30,18:00,18:30',
      phone: '010-65058888',
    },
    {
      name: '大宅门涮肉(后海店)',
      cuisineType: 'hotpot',
      district: '西城区',
      address: '北京市西城区德胜门内大街172号',
      latitude: 39.9390,
      longitude: 116.3810,
      rating: 4.3,
      description: '老北京铜锅涮肉，手切鲜羊肉是招牌，后海景致尽收眼底。',
      priceLevel: 2,
      avgPricePerPerson: 130,
      openTime: '11:00',
      closeTime: '23:00',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '火锅,铜锅涮肉,老北京,手切羊肉,后海',
      imageUrl: '',
      totalSeats: 150,
      currentWaitMins: 20,
      availableSlots: '11:00,11:30,12:00,17:00,17:30,18:00,18:30,19:00',
      phone: '010-83288888',
    },

    // ── Buffet (自助) ────────────────────────────────────────────────────────
    {
      name: '丽思卡尔顿自助餐厅',
      cuisineType: 'buffet',
      district: '朝阳区',
      address: '北京市朝阳区华贸中心建国路甲83号',
      latitude: 39.9060,
      longitude: 116.4640,
      rating: 4.5,
      description: '五星级酒店自助，海鲜与甜品品质出众，环境奢华。',
      priceLevel: 3,
      avgPricePerPerson: 380,
      openTime: '06:30',
      closeTime: '22:00',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '自助,五星级,海鲜,甜品,商务',
      imageUrl: '',
      totalSeats: 200,
      currentWaitMins: 10,
      availableSlots: '11:30,12:00,17:30,18:00,18:30',
      phone: '010-59608888',
    },
    {
      name: '第六季自助餐厅',
      cuisineType: 'buffet',
      district: '海淀区',
      address: '北京市海淀区中关村大街19号',
      latitude: 39.9810,
      longitude: 116.3180,
      rating: 4.1,
      description: '高性价比自助餐，海鲜、烤肉、甜品种类丰富。',
      priceLevel: 2,
      avgPricePerPerson: 158,
      openTime: '11:00',
      closeTime: '21:30',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: false,
      tags: '自助,海鲜,烤肉,性价比',
      imageUrl: '',
      totalSeats: 300,
      currentWaitMins: 25,
      availableSlots: '11:00,11:30,12:00,17:00,17:30,18:00,18:30',
      phone: '010-82509988',
    },

    // ── Family (家庭餐厅) ────────────────────────────────────────────────────
    {
      name: '蓝蛙(三里屯店)',
      cuisineType: 'family',
      district: '朝阳区',
      address: '北京市朝阳区三里屯路19号太古里南区',
      latitude: 39.9340,
      longitude: 116.4535,
      rating: 4.3,
      description: '美式家庭餐厅，汉堡和奶昔是招牌，周末亲子brunch人气高。',
      priceLevel: 2,
      avgPricePerPerson: 130,
      openTime: '10:00',
      closeTime: '22:00',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: false,
      tags: '家庭餐厅,汉堡,brunch,亲子',
      imageUrl: '',
      totalSeats: 120,
      currentWaitMins: 15,
      availableSlots: '10:30,11:00,11:30,12:00,12:30,17:30,18:00,18:30,19:00',
      phone: '010-64178899',
    },
    {
      name: '新元素(国贸店)',
      cuisineType: 'family',
      district: '朝阳区',
      address: '北京市朝阳区建国门外大街1号国贸商城',
      latitude: 39.9070,
      longitude: 116.4540,
      rating: 4.2,
      description: '健康餐饮品牌，新鲜果汁、沙拉和三明治为特色。',
      priceLevel: 2,
      avgPricePerPerson: 100,
      openTime: '07:00',
      closeTime: '22:00',
      childFriendly: true,
      dietFriendly: true,
      hasPrivateRoom: false,
      tags: '家庭餐厅,健康,果汁,brunch',
      imageUrl: '',
      totalSeats: 100,
      currentWaitMins: 10,
      availableSlots: '08:00,08:30,09:00,11:30,12:00,12:30,17:30,18:00,18:30',
      phone: '010-65051234',
    },
    {
      name: 'Wagas(颐堤港店)',
      cuisineType: 'family',
      district: '朝阳区',
      address: '北京市朝阳区酒仙桥路18号颐堤港',
      latitude: 39.9795,
      longitude: 116.4915,
      rating: 4.1,
      description: '轻食连锁品牌，三明治、沙拉和咖啡简餐为主。',
      priceLevel: 2,
      avgPricePerPerson: 80,
      openTime: '08:00',
      closeTime: '22:00',
      childFriendly: true,
      dietFriendly: true,
      hasPrivateRoom: false,
      tags: '家庭餐厅,轻食,咖啡,三明治',
      imageUrl: '',
      totalSeats: 80,
      currentWaitMins: 5,
      availableSlots: '08:30,09:00,09:30,11:00,11:30,12:00,12:30,17:30,18:00',
      phone: '010-84260168',
    },

    // ── Diet (轻食/减脂餐) ───────────────────────────────────────────────────
    {
      name: '沙野轻食(望京店)',
      cuisineType: 'diet',
      district: '朝阳区',
      address: '北京市朝阳区望京SOHO T1',
      latitude: 39.9900,
      longitude: 116.4760,
      rating: 4.2,
      description: '主打低脂轻食沙拉，食材新鲜，卡路里标注清晰。',
      priceLevel: 1,
      avgPricePerPerson: 45,
      openTime: '10:00',
      closeTime: '21:00',
      childFriendly: false,
      dietFriendly: true,
      hasPrivateRoom: false,
      tags: '轻食,减脂,沙拉,低卡,健康',
      imageUrl: '',
      totalSeats: 40,
      currentWaitMins: 5,
      availableSlots: '11:00,11:30,12:00,12:30,17:30,18:00,18:30',
      phone: '010-64738888',
    },
    {
      name: '超级碗(中关村店)',
      cuisineType: 'diet',
      district: '海淀区',
      address: '北京市海淀区中关村大街27号',
      latitude: 39.9815,
      longitude: 116.3165,
      rating: 4.3,
      description: '健康谷物碗品牌，蛋白质碗和蔬果碗最受欢迎。',
      priceLevel: 1,
      avgPricePerPerson: 50,
      openTime: '10:00',
      closeTime: '21:00',
      childFriendly: false,
      dietFriendly: true,
      hasPrivateRoom: false,
      tags: '轻食,谷物碗,健康,高蛋白,减脂',
      imageUrl: '',
      totalSeats: 50,
      currentWaitMins: 0,
      availableSlots: '11:00,11:30,12:00,12:30,13:00,17:30,18:00,18:30,19:00',
      phone: '010-82668866',
    },
    {
      name: '甜心摇滚沙拉',
      cuisineType: 'diet',
      district: '西城区',
      address: '北京市西城区金融街购物中心',
      latitude: 39.9140,
      longitude: 116.3560,
      rating: 4.0,
      description: '主打沙拉和健康饮品，适合减脂和健身人群。',
      priceLevel: 1,
      avgPricePerPerson: 55,
      openTime: '10:00',
      closeTime: '20:30',
      childFriendly: false,
      dietFriendly: true,
      hasPrivateRoom: false,
      tags: '轻食,沙拉,减脂,健身',
      imageUrl: '',
      totalSeats: 30,
      currentWaitMins: 0,
      availableSlots: '11:00,11:30,12:00,12:30,17:00,17:30,18:00',
      phone: '010-66228899',
    },
    {
      name: '好色派沙拉',
      cuisineType: 'diet',
      district: '朝阳区',
      address: '北京市朝阳区朝阳大悦城',
      latitude: 39.9220,
      longitude: 116.5170,
      rating: 4.1,
      description: '颜值与营养并重的沙拉品牌，色彩缤纷赏心悦目。',
      priceLevel: 1,
      avgPricePerPerson: 48,
      openTime: '10:00',
      closeTime: '21:30',
      childFriendly: false,
      dietFriendly: true,
      hasPrivateRoom: false,
      tags: '轻食,沙拉,颜值,健康,减脂',
      imageUrl: '',
      totalSeats: 40,
      currentWaitMins: 5,
      availableSlots: '11:00,11:30,12:00,12:30,17:30,18:00,18:30,19:00',
      phone: '010-85522299',
    },

    // ── Korean (韩餐) ────────────────────────────────────────────────────────
    {
      name: '姜虎东白丁(望京店)',
      cuisineType: 'korean',
      district: '朝阳区',
      address: '北京市朝阳区望京西路50号',
      latitude: 39.9875,
      longitude: 116.4730,
      rating: 4.3,
      description: '韩国人气烤肉品牌，由韩娱巨星姜虎东创办，烤肉配生菜包饭。',
      priceLevel: 2,
      avgPricePerPerson: 120,
      openTime: '11:00',
      closeTime: '23:00',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '韩餐,烤肉,姜虎东,望京',
      imageUrl: '',
      totalSeats: 120,
      currentWaitMins: 20,
      availableSlots: '11:30,12:00,12:30,17:30,18:00,18:30,19:00,19:30',
      phone: '010-84722777',
    },
    {
      name: '炸鸡情侣(五道口店)',
      cuisineType: 'korean',
      district: '海淀区',
      address: '北京市海淀区成府路35号',
      latitude: 39.9920,
      longitude: 116.3380,
      rating: 4.1,
      description: '韩式炸鸡与啤酒，多口味酱料选择，深夜解馋首选。',
      priceLevel: 1,
      avgPricePerPerson: 65,
      openTime: '11:00',
      closeTime: '23:00',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: false,
      tags: '韩餐,炸鸡,啤酒,深夜食堂',
      imageUrl: '',
      totalSeats: 60,
      currentWaitMins: 10,
      availableSlots: '11:30,12:00,12:30,17:30,18:00,18:30,19:00,19:30,20:00',
      phone: '010-62518888',
    },
    {
      name: '正一味',
      cuisineType: 'korean',
      district: '西城区',
      address: '北京市西城区西单北大街131号西单大悦城',
      latitude: 39.9120,
      longitude: 116.3740,
      rating: 4.0,
      description: '韩式简餐连锁，石锅拌饭和大酱汤为招牌。',
      priceLevel: 1,
      avgPricePerPerson: 45,
      openTime: '10:00',
      closeTime: '21:30',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: false,
      tags: '韩餐,石锅拌饭,简餐,实惠',
      imageUrl: '',
      totalSeats: 50,
      currentWaitMins: 5,
      availableSlots: '11:00,11:30,12:00,12:30,17:00,17:30,18:00,18:30,19:00',
      phone: '010-66518866',
    },
    {
      name: '明洞阿姨',
      cuisineType: 'korean',
      district: '丰台区',
      address: '北京市丰台区方庄路18号',
      latitude: 39.8620,
      longitude: 116.4300,
      rating: 4.2,
      description: '正宗韩式料理，部队火锅和韩式炸鸡最受欢迎。',
      priceLevel: 1,
      avgPricePerPerson: 75,
      openTime: '11:00',
      closeTime: '22:00',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: false,
      tags: '韩餐,部队火锅,炸鸡,实惠',
      imageUrl: '',
      totalSeats: 70,
      currentWaitMins: 10,
      availableSlots: '11:00,11:30,12:00,12:30,17:30,18:00,18:30,19:00',
      phone: '010-67658888',
    },

    // ── Thai (泰餐) ──────────────────────────────────────────────────────────
    {
      name: '暹罗之泰(国贸店)',
      cuisineType: 'thai',
      district: '朝阳区',
      address: '北京市朝阳区建国门外大街1号国贸商城',
      latitude: 39.9080,
      longitude: 116.4550,
      rating: 4.4,
      description: '京城知名泰餐厅，冬阴功汤和芒果糯米饭是必点。',
      priceLevel: 2,
      avgPricePerPerson: 140,
      openTime: '11:00',
      closeTime: '22:00',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '泰餐,冬阴功,芒果糯米饭,东南亚',
      imageUrl: '',
      totalSeats: 100,
      currentWaitMins: 15,
      availableSlots: '11:00,11:30,12:00,17:30,18:00,18:30,19:00',
      phone: '010-65059999',
    },
    {
      name: '雅谷',
      cuisineType: 'thai',
      district: '东城区',
      address: '北京市东城区东四十条22号',
      latitude: 39.9350,
      longitude: 116.4230,
      rating: 4.3,
      description: '胡同里的泰式小馆，绿咖喱和泰式炒河粉地道可口。',
      priceLevel: 2,
      avgPricePerPerson: 110,
      openTime: '11:00',
      closeTime: '22:00',
      childFriendly: false,
      dietFriendly: false,
      hasPrivateRoom: false,
      tags: '泰餐,胡同,绿咖喱,泰式炒河粉',
      imageUrl: '',
      totalSeats: 60,
      currentWaitMins: 10,
      availableSlots: '11:30,12:00,12:30,17:30,18:00,18:30,19:00',
      phone: '010-64008888',
    },

    // ── Italian (意大利餐) ───────────────────────────────────────────────────
    {
      name: '萨莉亚(中关村店)',
      cuisineType: 'italian',
      district: '海淀区',
      address: '北京市海淀区中关村大街15号',
      latitude: 39.9810,
      longitude: 116.3170,
      rating: 3.8,
      description: '平价意式连锁餐厅，披萨和意面价格亲民，学生最爱。',
      priceLevel: 1,
      avgPricePerPerson: 40,
      openTime: '10:30',
      closeTime: '21:30',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: false,
      tags: '意大利餐,平价,披萨,意面,学生',
      imageUrl: '',
      totalSeats: 80,
      currentWaitMins: 5,
      availableSlots: '11:00,11:30,12:00,12:30,13:00,17:00,17:30,18:00,18:30,19:00,19:30',
      phone: '010-82669999',
    },
    {
      name: '意库(三里屯店)',
      cuisineType: 'italian',
      district: '朝阳区',
      address: '北京市朝阳区三里屯路19号太古里北区',
      latitude: 39.9350,
      longitude: 116.4540,
      rating: 4.4,
      description: '精品意式餐厅，手工薄底披萨和提拉米苏是招牌。',
      priceLevel: 2,
      avgPricePerPerson: 150,
      openTime: '11:00',
      closeTime: '23:00',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '意大利餐,薄底披萨,提拉米苏,三里屯',
      imageUrl: '',
      totalSeats: 90,
      currentWaitMins: 20,
      availableSlots: '11:30,12:00,12:30,17:30,18:00,18:30,19:00',
      phone: '010-64178866',
    },
    {
      name: 'Mammamia玛玛咪雅',
      cuisineType: 'italian',
      district: '西城区',
      address: '北京市西城区金融街购物中心B1',
      latitude: 39.9135,
      longitude: 116.3565,
      rating: 4.2,
      description: '正宗那不勒斯风味，窑烤披萨香气四溢。',
      priceLevel: 2,
      avgPricePerPerson: 120,
      openTime: '11:00',
      closeTime: '21:30',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: false,
      tags: '意大利餐,窑烤披萨,那不勒斯',
      imageUrl: '',
      totalSeats: 70,
      currentWaitMins: 10,
      availableSlots: '11:00,11:30,12:00,12:30,17:30,18:00,18:30,19:00',
      phone: '010-66229988',
    },

    // ── Additional restaurants for more coverage ─────────────────────────────
    {
      name: '东来顺(王府井店)',
      cuisineType: 'chinese',
      district: '东城区',
      address: '北京市东城区王府井大街198号',
      latitude: 39.9145,
      longitude: 116.4115,
      rating: 4.3,
      description: '百年涮羊肉老字号，铜锅炭火，鲜切羊肉入口即化。',
      priceLevel: 2,
      avgPricePerPerson: 150,
      openTime: '11:00',
      closeTime: '21:30',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '中餐,涮羊肉,老字号,铜锅',
      imageUrl: '',
      totalSeats: 250,
      currentWaitMins: 25,
      availableSlots: '11:00,11:30,12:00,17:00,17:30,18:00,18:30,19:00',
      phone: '010-65139661',
    },
    {
      name: '鼎泰丰(国贸店)',
      cuisineType: 'chinese',
      district: '朝阳区',
      address: '北京市朝阳区建国门外大街1号国贸商城',
      latitude: 39.9082,
      longitude: 116.4548,
      rating: 4.4,
      description: '源自台湾的小笼包名店，18褶小笼包精致可口。',
      priceLevel: 2,
      avgPricePerPerson: 130,
      openTime: '11:00',
      closeTime: '21:30',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '中餐,小笼包,台湾,精致',
      imageUrl: '',
      totalSeats: 120,
      currentWaitMins: 30,
      availableSlots: '11:00,11:30,12:00,17:30,18:00,18:30',
      phone: '010-65056888',
    },
    {
      name: '张妈妈特色川味馆',
      cuisineType: 'chinese',
      district: '海淀区',
      address: '北京市海淀区五道口成府路29号',
      latitude: 39.9925,
      longitude: 116.3375,
      rating: 4.1,
      description: '地道四川家常菜，麻婆豆腐和回锅肉是学生最爱。',
      priceLevel: 1,
      avgPricePerPerson: 55,
      openTime: '11:00',
      closeTime: '22:00',
      childFriendly: false,
      dietFriendly: false,
      hasPrivateRoom: false,
      tags: '中餐,川菜,麻辣,家常,学生',
      imageUrl: '',
      totalSeats: 60,
      currentWaitMins: 10,
      availableSlots: '11:00,11:30,12:00,12:30,17:30,18:00,18:30,19:00,19:30',
      phone: '010-62519999',
    },
    {
      name: '丰泽园饭店',
      cuisineType: 'chinese',
      district: '西城区',
      address: '北京市西城区珠市口西大街83号',
      latitude: 39.8940,
      longitude: 116.3970,
      rating: 4.4,
      description: '鲁菜名店，葱烧海参和九转大肠是经典招牌。',
      priceLevel: 3,
      avgPricePerPerson: 220,
      openTime: '11:00',
      closeTime: '21:30',
      childFriendly: false,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '中餐,鲁菜,老字号,海参',
      imageUrl: '',
      totalSeats: 200,
      currentWaitMins: 15,
      availableSlots: '11:00,11:30,12:00,17:00,17:30,18:00,18:30',
      phone: '010-63032828',
    },
    {
      name: '小吊梨汤(中关村店)',
      cuisineType: 'chinese',
      district: '海淀区',
      address: '北京市海淀区中关村广场步行街',
      latitude: 39.9830,
      longitude: 116.3180,
      rating: 4.2,
      description: '京味创意菜，梨汤滋润，菜品精致有特色。',
      priceLevel: 2,
      avgPricePerPerson: 95,
      openTime: '11:00',
      closeTime: '21:30',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '中餐,京味,梨汤,创意菜',
      imageUrl: '',
      totalSeats: 100,
      currentWaitMins: 15,
      availableSlots: '11:00,11:30,12:00,12:30,17:00,17:30,18:00,18:30,19:00',
      phone: '010-82667777',
    },
    {
      name: '紫光园(通州万达店)',
      cuisineType: 'chinese',
      district: '通州区',
      address: '北京市通州区新华西街58号万达广场',
      latitude: 39.9070,
      longitude: 116.6560,
      rating: 4.0,
      description: '北京老字号清真餐厅，烧饼和炒疙瘩是招牌。',
      priceLevel: 1,
      avgPricePerPerson: 50,
      openTime: '06:30',
      closeTime: '21:30',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: false,
      tags: '中餐,清真,老字号,烧饼',
      imageUrl: '',
      totalSeats: 120,
      currentWaitMins: 5,
      availableSlots: '07:00,07:30,08:00,11:00,11:30,12:00,12:30,17:30,18:00,18:30',
      phone: '010-60538888',
    },
    {
      name: '松子日本料理',
      cuisineType: 'japanese',
      district: '朝阳区',
      address: '北京市朝阳区亮马桥路48号',
      latitude: 39.9500,
      longitude: 116.4620,
      rating: 4.4,
      description: '北京老牌日料店，刺身拼盘和天妇罗口碑极佳。',
      priceLevel: 2,
      avgPricePerPerson: 180,
      openTime: '11:00',
      closeTime: '22:00',
      childFriendly: false,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '日料,刺身,天妇罗,老牌',
      imageUrl: '',
      totalSeats: 80,
      currentWaitMins: 10,
      availableSlots: '11:30,12:00,12:30,17:30,18:00,18:30,19:00',
      phone: '010-64618866',
    },
    {
      name: '聚宝源(牛街总店)',
      cuisineType: 'hotpot',
      district: '西城区',
      address: '北京市西城区牛街5号',
      latitude: 39.8935,
      longitude: 116.3565,
      rating: 4.5,
      description: '牛街最火的涮肉馆，手切鲜羊肉和烧饼是绝配。',
      priceLevel: 2,
      avgPricePerPerson: 110,
      openTime: '11:00',
      closeTime: '22:00',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '火锅,涮羊肉,清真,手切鲜羊肉,牛街',
      imageUrl: '',
      totalSeats: 200,
      currentWaitMins: 45,
      availableSlots: '11:00,11:30,12:00,17:00,17:30,18:00',
      phone: '010-83545678',
    },
    {
      name: '南门涮肉(后海店)',
      cuisineType: 'hotpot',
      district: '西城区',
      address: '北京市西城区南官房胡同1号',
      latitude: 39.9395,
      longitude: 116.3885,
      rating: 4.4,
      description: '老北京铜锅涮肉，临后海而坐，别有风味。',
      priceLevel: 2,
      avgPricePerPerson: 120,
      openTime: '11:00',
      closeTime: '23:00',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '火锅,铜锅涮肉,后海,老北京',
      imageUrl: '',
      totalSeats: 160,
      currentWaitMins: 30,
      availableSlots: '11:00,11:30,12:00,17:00,17:30,18:00,18:30',
      phone: '010-83228888',
    },
    {
      name: '鲜辣鲜香(大兴店)',
      cuisineType: 'chinese',
      district: '大兴区',
      address: '北京市大兴区黄村东大街38号',
      latitude: 39.7270,
      longitude: 116.3410,
      rating: 4.0,
      description: '地道川湘菜馆，水煮鱼和剁椒鱼头是招牌。',
      priceLevel: 1,
      avgPricePerPerson: 65,
      openTime: '11:00',
      closeTime: '21:30',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '中餐,川菜,湘菜,麻辣',
      imageUrl: '',
      totalSeats: 80,
      currentWaitMins: 5,
      availableSlots: '11:00,11:30,12:00,12:30,17:00,17:30,18:00,18:30,19:00',
      phone: '010-69228888',
    },
    {
      name: '猫抓烤肉(石景山店)',
      cuisineType: 'chinese',
      district: '石景山区',
      address: '北京市石景山区石景山路22号长城大厦',
      latitude: 39.9040,
      longitude: 116.2290,
      rating: 4.1,
      description: '韩式烤肉风味与中式调料结合，年轻人聚餐首选。',
      priceLevel: 2,
      avgPricePerPerson: 95,
      openTime: '11:00',
      closeTime: '22:00',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: false,
      tags: '烤肉,韩式,聚餐,年轻人',
      imageUrl: '',
      totalSeats: 100,
      currentWaitMins: 10,
      availableSlots: '11:00,11:30,12:00,12:30,17:30,18:00,18:30,19:00,19:30',
      phone: '010-68886666',
    },
    {
      name: '和彩日料(顺义店)',
      cuisineType: 'japanese',
      district: '顺义区',
      address: '北京市顺义区天竺镇裕翔路99号',
      latitude: 40.0600,
      longitude: 116.5600,
      rating: 4.2,
      description: '机场附近的精品日料，刺身新鲜，环境雅致。',
      priceLevel: 2,
      avgPricePerPerson: 160,
      openTime: '11:00',
      closeTime: '21:30',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '日料,刺身,寿司,顺义',
      imageUrl: '',
      totalSeats: 80,
      currentWaitMins: 5,
      availableSlots: '11:30,12:00,12:30,17:30,18:00,18:30,19:00',
      phone: '010-80498888',
    },
    {
      name: '昌平阳坊胜利涮羊肉',
      cuisineType: 'hotpot',
      district: '昌平区',
      address: '北京市昌平区阳坊镇中心街',
      latitude: 40.1200,
      longitude: 116.0800,
      rating: 4.3,
      description: '昌平名店，以地道涮羊肉闻名，羊肉鲜嫩不膻。',
      priceLevel: 1,
      avgPricePerPerson: 80,
      openTime: '11:00',
      closeTime: '21:30',
      childFriendly: true,
      dietFriendly: false,
      hasPrivateRoom: true,
      tags: '火锅,涮羊肉,昌平,地道',
      imageUrl: '',
      totalSeats: 120,
      currentWaitMins: 10,
      availableSlots: '11:00,11:30,12:00,12:30,17:00,17:30,18:00,18:30,19:00',
      phone: '010-69768888',
    },
  ];

  const restaurants: Awaited<ReturnType<typeof db.restaurant.create>>[] = [];
  for (const r of restaurantData) {
    const restaurant = await db.restaurant.create({ data: r });
    restaurants.push(restaurant);
  }
  console.log(`Created ${restaurants.length} restaurants`);

  // ─── Summary ───────────────────────────────────────────────────────────────
  console.log('\n=== Seed Summary ===');
  console.log(`Users: ${users.length}`);
  console.log(`Venues: ${venues.length}`);
  console.log(`Restaurants: ${restaurants.length}`);
  console.log('Seeding complete!');
}

main()
  .catch((e) => {
    console.error('Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
